### ISSUE TITLE
Latest hook changes might have a bug: InvalidManifestError

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#346] opened 2020-10-17 19:12 UTC
Just after I reinstalled pre-commit (after getting the latest changes) and then I ran `precommit run --all` or even tried to `git commit` my changes I get this error:

```
An error has occurred: InvalidManifestError:
==> File /Users/user/.cache/pre-commit/repo8m9u7jls/.pre-commit-hooks.yaml
==> At Hook(id='nbqa')
==> At key: types
==> At index 0
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
Check the log at /Users/user/.cache/pre-commit/pre-commit.log
```

Workaround: uninstall `precommit` and we can continue to use git commit

**Comment by s-weigand** [comment] 2020-10-17 19:37
Works fine for me.
Try `pip install -U pre-commit` or even `pip install --force-reinstall -U pre-commit`

**Comment by s-weigand** [comment] 2020-10-17 19:41
Also, we might want to add this to our `.pre-commit-config.yaml`
```yaml
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.7.1
    hooks:
      - id: validate_manifest
```
and add tests for the hook.
Run as hook vs. run from CLI.

**Comment by s-weigand** [comment] 2020-10-17 20:21
My guess is that your `pre-commit` installation is broken since this also worked for me
```console
$ pre-commit try-repo https://github.com/nbQA-dev/nbQA
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/nbQA-dev/nbQA
    rev: ef22306c031274b1bd34d2c50c7f1c4d1cfeb96c
    hooks:
    -   id: nbqa
    -   id: nbqa-black
    -   id: nbqa-doctest
    -   id: nbqa-flake8
    -   id: nbqa-isort
    -   id: nbqa-mypy
    -   id: nbqa-pylint
    -   id: nbqa-pyupgrade
===============================================================================
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:black.
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:flake8.
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:isort.
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:mypy.
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:pylint.
[INFO] Initializing environment for https://github.com/nbQA-dev/nbQA:pyupgrade.
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
nbqa.................................................(no files to check)Skipped
nbqa-black...........................................(no files to check)Skipped
nbqa-doctest.........................................(no files to check)Skipped
nbqa-flake8..........................................(no files to check)Skipped
nbqa-isort...........................................(no files to check)Skipped
nbqa-mypy............................................(no files to check)Skipped
nbqa-pylint..........................................(no files to check)Skipped
nbqa-pyupgrade.......................................(no files to check)Skipped
```

**Comment by neomatrix369** [comment] 2020-10-17 20:40
Reinstalling it worked. But I'm surprised why this happened.

**Comment by neomatrix369** [comment] 2020-10-17 20:40
```
pre-commit run --all
[INFO] Initializing environment for https://www.github.com/nbQA-dev/nbQA:black.
[INFO] Installing environment for https://www.github.com/nbQA-dev/nbQA.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
nbqa-black...............................................................Passed
```

**Comment by neomatrix369** [comment] 2020-10-17 20:41
I'm happy to close this issue if there isn't anything else to be done

**Comment by MarcoGorelli** [comment] 2020-10-18 10:03
Awesome, thanks for the report!

How about we close it when
```
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.7.1
    hooks:
      - id: validate_manifest
```
is added here as a hook?

**Comment by MarcoGorelli** [comment] 2020-10-18 10:08
> Reinstalling it worked. But I'm surprised why this happened.

I _guess_ is that you might have had an old version of pre-commit where the tag `jupyter` hadn't been defined yet - had you ever installed it in the past?

**Comment by neomatrix369** [comment] 2020-10-18 11:33
> > Reinstalling it worked. But I'm surprised why this happened.
> 
> I _guess_ is that you might have had an old version of pre-commit where the tag `jupyter` hadn't been defined yet - had you ever installed it in the past?

Yes possible, I have used precommit with black in the past, but maybe the latest work with nbqa might have changed things.

I'm all good now. Do we need to amend any config on my end? Feel free to create a new PR when you are ready. This issue can close when you are up for it.

**Comment by MarcoGorelli** [comment] 2020-10-18 12:26
> Do we need to amend any config on my end?

If you want to include pre-commit in your requirements-dev.txt, then perhaps you could specify 2.7.1 as the minimum version? (maybe a smaller minimum version would work, but like this at least you're sure that nobody will be tripped up by unrecognized tags)

**Closed** 2020-10-18 12:50 UTC
Labels: bug, good first issue

**Comment by s-weigand** [comment] 2020-10-18 15:51
There is also the [`minimum_pre_commit_version`](https://pre-commit.com/#top_level-minimum_pre_commit_version) option we can set in our  `.pre-commit-hooks.yaml`.
But my guess is the real problem was the version of `identify`, which [looks like to have added `jupyter` in `v1.4.20`](https://github.com/pre-commit/identify/commit/8039023a57cfbb40561700ffb491be71bfc8b934).
But even the master version of `pre-commit`, [only requires `identify>=1.0.0`](https://github.com/pre-commit/pre-commit/blob/9e4754fb4aa645e2b7b7938b529fdf8847de97f7/setup.cfg#L26).

So I see two options to solve this problem:

1. Don't use `types: [jupyter]` but
  ```yaml
  types: [file]
  files: \.ipynb$
  ```
  which is more robust and pretty much the way `identify` does it itselfe.

2. Kindly ask `pre-commit` to add a `minimum_identify_version` as an option in `.pre-commit-hooks.yaml` (even so the error message basically tells you what to do)
  > Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

(3.) Mention in the docs that users need to at least have `identify>=1.4.20`

IMHO 1. would be at least a good hotfix.

**Comment by MarcoGorelli** [comment] 2020-10-18 15:56
As a general comment, for Jupyter notebooks this is probably fine, but `types` gives you the benefit that it can identify non-extensioned files, so I wouldn't replace types with files everywhere :smile:

**Comment by barakreif** [comment] 2020-11-04 13:45
JUST FYI we have the same issue and none of the mitigations mentioned here resolved it.
caveats: 1 it was a brew installed python 3.6 venv, in docker it didn't reproduce, also didn't reproduce in a conda env.

**Comment by MarcoGorelli** [comment] 2020-11-04 14:22
Hi @barakreif 

Thanks for your report!

Do you mean that you also got the error
```
An error has occurred: InvalidManifestError:
==> File /Users/user/.cache/pre-commit/repo8m9u7jls/.pre-commit-hooks.yaml
==> At Hook(id='nbqa')
==> At key: types
==> At index 0
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
Check the log at /Users/user/.cache/pre-commit/pre-commit.log
```
?

If so, could you please let us know which pre-commit version you're running? i.e. show us the output of
```
pre-commit --version
```

Thanks :pray:

**Comment by s-weigand** [comment] 2020-11-04 14:26
@barakreif Could you provide some more information?
The following would help
```console
$ which pre-commit
$ pre-commit --version
$ pip freeze | grep identify
$ which identify-cli
```
Somehow `identify-cli` doesn't have a `--version` flag ... 😢 

My guess is that `pre-commit` with a too old version is installed globally, and identify was updated in the venv.

**Comment by barakreif** [comment] 2020-11-04 14:28
started with 2.2.0 updated to 2.7.1 it attempt to mitigate, when updated -I identity said we already had latest

> @barakreif Could you provide some more information?
> The following would help
> 
> ```
> $ which pre-commit
> $ pre-commit --version
> $ pip freeze | grep identify
> $ which identify-cli
> ```
> 
> Somehow `identify-cli` doesn't have a `--version` flag ... 😢
> 
> My guess is that `pre-commit` with a too old version is installed globally, and identify was updated in the venv.

started with 2.2.0 updated to latest it attempt to mitigate, when updated -U identity said we already had latest

getting you the above

**Comment by s-weigand** [comment] 2020-11-04 14:40
When updating `pre-commit`, the dependencies won't be updated if the minimum requirement is fulfilled.
Could you check if the following command solves your problem?
```console
$ pip install -U --upgrade-strategy=eager pre-commit
```


 > --upgrade-strategy <upgrade_strategy>
   Determines how dependency upgrading should be handled [default: only-if-needed]. "eager" - dependencies are upgraded regardless of whether the currently installed version satisfies the requirements of the upgraded package(s). "only-if-needed" -  are upgraded only when they do not satisfy the requirements of the upgraded package(s).


@MarcoGorelli Maybe we should have a `trouble-shooting` section in the docs.

**Comment by MarcoGorelli** [comment] 2020-11-04 14:49
@s-weigand yup, that's probably a good idea - do you feel like opening an issue to keep track of this and/or making a new docs section? Else I'll get round to it at the weekend

**Comment by barakreif** [comment] 2020-11-04 19:30
> > @barakreif Could you provide some more information?
> > The following would help
> > ```
> > $ which pre-commit
> > $ pre-commit --version
> > $ pip freeze | grep identify
> > $ which identify-cli
> > ```
> > 
> > 
> > Somehow `identify-cli` doesn't have a `--version` flag ... 😢
> > My guess is that `pre-commit` with a too old version is installed globally, and identify was updated in the venv.
> 
> started with 2.2.0 updated to latest it attempt to mitigate, when updated -U identity said we already had latest
> 
> getting you the above

```shell
% which pre-commit
/usr/local/bin/pre-commit
(venv)  % pre-commit --version
pre-commit 2.7.1
(venv) % pip freeze | grep identify
identify==1.5.9
(venv) % which identify-cli
/usr/local/bin/identify-cli
```

**Comment by MarcoGorelli** [comment] 2020-11-05 07:30
Thanks @barakreif for the info.  And, just to confirm, running

```
pre-commit try-repo https://github.com/nbQA-dev/nbQA
```
gives you 


Looks like you have a global install of pre-commit and of identify.
I don't know what @s-weigand had in mind, but I would suggest to first uninstall your global install of `pre-commit` and `identify`, and then, in your virtual environment (`venv`), install `pip install -U pre-commit`.

It sounds like the issue isn't connected with nbqa - I guess you also can't run
```
pre-commit try-repo https://github.com/kynan/nbstripout
```
?

Anyway, we're keen to help you resolve the issue, and feel free to write to us on gitter (https://gitter.im/nbQA/nbQA) if that's easier

**Comment by barakreif** [comment] 2020-11-05 08:22
> Thanks @barakreif for the info. And, just to confirm, running
> 
> ```
> pre-commit try-repo https://github.com/nbQA-dev/nbQA
> ```
> 
> gives you
> 
> ```
> An error has occurred: InvalidManifestError:
> ==> File /Users/user/.cache/pre-commit/repo8m9u7jls/.pre-commit-hooks.yaml
> ==> At Hook(id='nbqa')
> ==> At key: types
> ==> At index 0
> =====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
> Check the log at /Users/user/.cache/pre-commit/pre-commit.log
> ```
> 
> Looks like you have a global install of pre-commit and of identify.
> I don't know what @s-weigand had in mind, but I would suggest to first uninstall your global install of `pre-commit` and `identify`, and then, in your virtual environment (`venv`), install `pip install -U pre-commit`.
> 
> It sounds like the issue isn't connected with nbqa - I guess you also can't run `pre-commit try-repo https://github.com/kynan/nbstripout`?
> 
> Anyway, we're keen to help you resolve the issue, and feel free to write to us on gitter (https://gitter.im/nbQA/nbQA) if that's easier

a. so just removing the nbqa entries from the `.pre-commit-config.yaml` made pre-commit work as intended, so probably an `identify` issue.
b. I feel like my personal pride compels me to note that its a co-workers env not mine (insert ego related comments here) regardless we've since moved  to a venv stemming from brew python(3.6)  to a conda (python 3.7.5) while still using pip and not conda to install and all issues have been resolved. 

i am going for to assume something just got corrupted in the local install and conventional pip (force) updates and reinstalls  didn't fix it.

I left the older one aside and will play around later with the above.

**Comment by MarcoGorelli** [comment] 2020-11-05 08:25
> and all issues have been resolved.
