### ISSUE TITLE
Multiline terminal command isn't processed properly

### ISSUE THREAD

**Issue by ivanmkc** [nbQA-dev/nbQA#657] opened 2021-09-01 23:05 UTC
I've included two notebooks, which are identical except for the terminal command.

-  one with a single-line terminal command
```
! bq --location=US load --autodetect --skip_leading_rows=1 --source_format=CSV {dataset_id}.us_states_local_file 'resources/us-states.csv'
```

- one with a multi-line terminal command
```
!bq \
--location=US load \
--autodetect \
--skip_leading_rows=1 \
--source_format=CSV \
{dataset_id}.us_states_local_file \
'resources/us-states.csv'
```

The one with multiline doesn't process properly, so when I run nbqa with `black`, I get:
```
Running black...
error: cannot format notebooks/official/bigquery_command_line_tool.ipynb: Cannot parse: cell_6:2:5: --lo 0x6AA55214
```

[Archive.zip](https://github.com/nbQA-dev/nbQA/files/7094964/Archive.zip)

**Comment by loferris** [comment] 2021-09-01 23:17
I have had an almost identical error with this file and in addition
`!bq load \
--location=US \` 
etc. is auto-revised by `black` to the second block @ivanmkc mentions above, which then throws the same error. This syntax should also be acceptable. https://cloud.google.com/bigquery/docs/bq-command-line-tool#loading_data

**Comment by MarcoGorelli** [comment] 2021-09-02 07:06
Hey @loferris , thanks for the report! I'll take a look

Does this also happen when you run `black` on the notebook directly? (As of version 21.8b0, it has support for notebooks)

**Comment by MarcoGorelli** [comment] 2021-09-02 07:32
Can't reproduce either example with the latest version (1.1.0):
```console
(venv) marcogorelli@OVMG025 mcve % cat Untitled.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f013878e-4ee4-4d12-ba40-2afac49d4c29",
   "metadata": {},
   "outputs": [],
   "source": [
    "!bq \\\n",
    "--location=US load \\\n",
    "--autodetect \\\n",
    "--skip_leading_rows=1 \\\n",
    "--source_format=CSV \\\n",
    "{dataset_id}.us_states_local_file \\\n",
    "'resources/us-states.csv'\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "good-bayesian",
   "language": "python",
   "name": "good-bayesian"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
(venv) marcogorelli@OVMG025 mcve % nbqa black Untitled.ipynb
All done! ✨ 🍰 ✨
1 file left unchanged.
```

From https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/eed2ac7af3d552f16690c858439f22347a4d616e/.github/workflows/linter/requirements.txt it looks like you're on on an old version of nbQA

Please upgrade to the latest version (1.1.0) or use `black` directly (I contributed the PR https://github.com/psf/black/pull/2357 , the logic is almost the same as nbQA's, it just works cell-by-cell)

If this still doesn't work for you with the latest version of nbqa, let me know and I'll reopen

**Comment by loferris** [comment] 2021-09-09 22:15
@MarcoGorelli With the linter as currently defined, the same error is occurring with the updated version of nbqa. I am now seeing about using black directly to see if this solves the problem.

**Comment by MarcoGorelli** [comment] 2021-09-09 22:25
Thanks @loferris - reopening for now then, I'll take another look

**Comment by loferris** [comment] 2021-09-09 22:26
when I run the latest version of black directly `python3 -m black "$notebook"` I get a runtime error and a prompt to open a bug report with nbQA

**Comment by MarcoGorelli** [comment] 2021-09-10 07:39
I just ran both `nbqa` and `black` on the files which @ivanmkc mentioned, and got no error. Please 
1. show the output of:
  ```
  nbqa --version
  black --version
  ```
2. share a notebook which reproduces the issue
3. show the exact command you ran, along with the exact output

>  when I run the latest version of black directly python3 -m black "$notebook" I get a runtime error and a prompt to open a bug report with nbQA

There's no way that this could happen, `black`'s codebase makes no mention of nbQA

**Comment by loferris** [comment] 2021-09-10 23:17
1. `nbqa --version` was 0.6.0 on my machine (it's updated to 1.1.0 in the linter) but I upgraded it to 1.1.0 for the rest of this comment. `black --version` was 20.8b1 on my machine, upgraded to 21.8b0 for the rest of this comment. [This was because I didn't re-install the linter after changing the requirements `.txt` file.]
2. Currently all of the notebooks are failing in this repo, with the same error, captured below. The exact problem notebook `black` wasn't able to parse before is here: https://github.com/GoogleCloudPlatform/bigquery-notebooks/blob/update_linter/notebooks/official/template_notebooks/bigquery_command_line_tool.ipynb
3. Here's the code the linter runs:
`if [ "$is_test" = true ] ; then
                echo "Running nbfmt..."
                python3 -m tensorflow_docs.tools.nbfmt --remove_outputs --test "$notebook"
                NBFMT_RTN=$?
                # echo "Running black..."
                # python3 -m nbqa black "$notebook" --check
                # BLACK_RTN=$?
                echo "Running pyupgrade..."
                python3 -m nbqa pyupgrade "$notebook"
                PYUPGRADE_RTN=$?
                echo "Running isort..."
                python3 -m nbqa isort "$notebook" --check
                ISORT_RTN=$?
                echo "Running flake8..."
                python3 -m nbqa flake8 "$notebook" --show-source --extend-ignore=W391,E501,F821,E402,F404,W503,W291,E203,E999,E111,E113 
                FLAKE8_RTN=$?
            else
                echo "Running black..."
                python3 -m black "$notebook"
                BLACK_RTN=$?            
                echo "Running pyupgrade..."
                python3 -m nbqa pyupgrade "$notebook"
                PYUPGRADE_RTN=$?
                echo "Running isort..."
                python3 -m nbqa isort "$notebook"
                ISORT_RTN=$?
                echo "Running nbfmt..."
                python3 -m tensorflow_docs.tools.nbfmt --remove_outputs "$notebook"
                NBFMT_RTN=$?
                echo "Running flake8..."
                python3 -m nbqa flake8 "$notebook" --show-source --extend-ignore=W391,E501,F821,E402,F404,W503,W291,E203,E999,E111,E113
                FLAKE8_RTN=$?                 
            fi

            NOTEBOOK_RTN="0"`
(the file is here: https://github.com/GoogleCloudPlatform/bigquery-notebooks/blob/update_linter/.github/workflows/linter/run_linter.sh)
The output is captured here: black is failing the same way and the same error comes up for each subsequent invocation of nbqa.
![Screen Shot 2021-09-10 at 4 08 03 PM](https://user-images.githubusercontent.com/50979514/132926825-0bfd935b-9058-4ee3-8b7b-6d689f4f2fe2.png)

Oh, and you're right, I misread the original error! `black` was running, but then all following `nbqa` commands were failing with the `JSONDecodeError`

**Comment by loferris** [comment] 2021-09-10 23:58
When I go to that line in the `.ipynb` its questioning this:
`'# Licensed under the Apache License, Version 2.0 (the "License");\n',`
With the first character - ' - being l11,c17.
Manually changing around the quotes cleared that error, but there seems to be further JSON nits it gets bothered by. Another thing worth mentioning is that these odd changes seemed to have happened after I ran `black` (I think), as I haven't been manually messing around with the header code and previously it had double-quote formatting.

**Comment by MarcoGorelli** [comment] 2021-09-11 06:07
OK, I see what's happened - you're missing the extra Jupyter requirements when running black on the notebooks, and so they're been formatted as if they were Python files.

If you want Jupyter support for `black`, you need to install it as

```
pip install -U black[jupyter]
```

I'd advise:
- checkout your notebooks to the original state
- `pip install -U black[jupyter]`
- run any other linting checks

**Comment by MarcoGorelli** [comment] 2021-09-11 08:08
As an aside, seeing as you're using `nbQA` at Google, I'd appreciate it if you could consider [sponsoring the project](https://github.com/sponsors/MarcoGorelli)

**Comment by MarcoGorelli** [comment] 2021-09-15 20:12
HI @ivanmkc and @loferris - it looks like https://github.com/GoogleCloudPlatform/bigquery-notebooks/pull/18/files , so I gather this is now resolved?

Closing for now then, but please do let me know if you run into any other issues 👍

**Closed by MarcoGorelli** 2021-09-15 20:12 UTC
Labels: needs info
