### ISSUE TITLE
nbqa ignore cells with "!" command execution, making tools like pylint fail

### ISSUE THREAD

**Issue by dnoliver** [nbQA-dev/nbQA#743] opened 2022-09-07 00:39 UTC
Pylint was giving me an "undefined variable error" in a notebook.
The variable was defined in cell, and used in other cell later.
Then I thought, "I can print whatever nbqa is scanning with cat, and run pylint on that output", and I got the same error. 
The commands examples are below:

```bash
nbqa --nbqa-dont-skip-bad-cells pylint -E --disable=E0401 notebook.py
nbqa --nbqa-shell cat notebook.ipynb > notebook.py
pylint  -E --disable=E0401 notebook.py
```

The exported notebook.py file didn't have the variables declaration.
Then I noticed all the code cells that run a command like `!ls -la` missing from notebook.py.
It happens that the missing variable is defined in one of those cells with commands, and given that nbqa apparently ignore all the content in them, the code processed by pyling didn't have the variable declaration.

I was taking a look at https://nbqa.readthedocs.io/en/latest/configuration.html#cell-magics and https://ipython.readthedocs.io/en/stable/interactive/magics.html, it seems like nbqa --nbqa-dont-skip-bad-cells --nbqa-process-cells sc should do the trick, but %sc is deprecated in favor of "!", and I gor the same result by using the option.

**Comment by dnoliver** [comment] 2022-09-07 01:25
Tried `nbconvert` as an alternative.

```bash
jupyter nbconvert --to script notebook.ipynb
pylint -E --disable=E0401 notebook.py
```

I didn't got the "undefined  variable" issue I got with nbqa. 
The "!cmd" calls where replaced by `get_ipython().getoutput(cmd)` calls. 

Should I use nbconvert instead to run pylint? or is this a valid use case for nbqa?

**Comment by MarcoGorelli** [comment] 2022-09-07 08:13
Hey @dnoliver thanks for the report

Could you produce a reproducible example please? E.g.:

- in cell1, put `...`
- in cell12, put `...`
- run `nbqa pylint ...`

**Comment by dnoliver** [comment] 2022-09-07 16:12
LOL this was not as trivial as I thought :D 

This is my notebook that reproduce the issue:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d333b7f9-a9e0-474d-ba0d-96f09fc023ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "foo = !whoami \\\n",
    "  && ls\n",
    "bar = foo[0].split('.')[0]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "954727dd-c098-413f-b8dd-4f41824dc33d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(f\"{bar}.mp4\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

```
root@7c2d148646f9:~/workspace# nbqa --nbqa-dont-skip-bad-cells --nbqa-shell pylint -E ./notebook.ipynb 
************* Module notebook
notebook.ipynb:cell_2:1:9: E0602: Undefined variable 'bar' (undefined-variable)
```

This is my proof that it runs

![image](https://user-images.githubusercontent.com/7730267/188927485-b171919e-31eb-4054-84c7-64994c76f450.png)

I took the container from this blog: https://towardsdatascience.com/how-to-run-jupyter-notebook-on-docker-7c9748ed209f

Funny thing is, if you remove the bash-like line break (\\), nbqa can process the notebook fine. The snippet below works

```
"source": [
    "foo = !whoami && ls\n",
    "bar = foo[0].split('.')[0]\n"
   ]
```

**Comment by MarcoGorelli** [comment] 2022-09-07 16:33
Ah I think it's because your cell contains a multi-line magic, which isn't handled, see [known limitations](https://nbqa.readthedocs.io/en/latest/known-limitations.html)

I'd suggest putting `bar = foo[0].split('.')[0]` in a separate cell

**Comment by MarcoGorelli** [comment] 2022-09-07 16:43
> Funny thing is, if you remove the bash-like line break (\), nbqa can process the notebook fine. The snippet below works

Yeah, that's exactly the issue - closing for now then (unless you have an idea for how to handle multi-line magics, in which case, please do send a PR)

**Closed by MarcoGorelli** 2022-09-07 16:43 UTC

**Comment by dnoliver** [comment] 2022-09-08 16:06
Got it, thanks for the help.
I was wondering why handling those multi-line magics is complex. 
Below is the result of extracting code with nbqa

```
# %%NBQA-CELL-SEP0cee9d
hash(0x679DEA7E)


# %%NBQA-CELL-SEP0cee9d
print(f"{bar}.mp4")
```

And this is the result with nbconvert (jupyter nbconvert --to=script notebook.ipynb)

```
#!/usr/bin/env python
# coding: utf-8

# In[ ]:

foo = get_ipython().getoutput('whoami    && ls')
bar = foo[0].split('.')[0]

# In[ ]:

print(f"{bar}.mp4")
```

So nbconvert is handling those multi-line magic gracefully. 

I also tried splitting the cells, but it still runs into pylint issue

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe970755-8ca2-4dd6-9acb-19b5a4e1a334",
   "metadata": {},
   "outputs": [],
   "source": [
    "foo = !whoami \\\n",
    "  && ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf734962-5636-420b-ae28-5cbb42cfa5a8",
   "metadata": {},
   "outputs": [],
   "source": [
    "bar = foo[0].split('.')[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "954727dd-c098-413f-b8dd-4f41824dc33d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(f\"{bar}.mp4\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

```
root@d3dd3c86075a:~/workspace# nbqa pylint -E ./notebook.ipynb 
************* Module notebook
notebook.ipynb:cell_2:1:6: E0602: Undefined variable 'foo' (undefined-variable)
```

```
# %%NBQA-CELL-SEP0a16db
hash(0xE3E58BFD)

# %%NBQA-CELL-SEP0a16db
bar = foo[0].split('.')[0]

# %%NBQA-CELL-SEP0a16db
print(f"{bar}.mp4")
```

I took a quick look at https://github.com/jupyter/nbconvert, couldn't find how they handle those multiline magics, but there must be some code to be borrowed from there :)

**Comment by MarcoGorelli** [comment] 2022-09-08 16:58
> foo = get_ipython().getoutput('whoami && ls')

That's the issue, the line break hasn't been preserved by nbconvert

**Comment by MarcoGorelli** [comment] 2022-09-08 16:59
> I also tried splitting the cells, but it still runs into pylint issue

You're still assigning to `foo` in a cell with a multi line magic, that's the issue
