### ISSUE TITLE
QUESTION: how do you measure the complexity of a block of code or blocks of code in the entire notebook?

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#258] opened 2020-09-24 12:40 UTC
I'm raising this just to discuss if there is a way to measure complexity of Python (or other language supported by a notebook)?

There's https://en.wikipedia.org/wiki/Cyclomatic_complexity that many languages have libraries for, I'm thinking there is one for Python as well.

In case your other analysis already covers this then please close this. Otherwise, it would be a helpful feature to have.

Maybe related to #259

**Comment by MarcoGorelli** [comment] 2020-09-24 12:59
Hi @neomatrix369 - thanks for opening this issue!

nbQA simply applies any standard Python code quality tool to a Jupyter Notebook - if you have a Python tool which calculates complexity, then using nbQA it should be possible to apply it to a notebook.

Do you know of any Python tool for calculating complexity?

**Comment by neomatrix369** [comment] 2020-09-24 13:10
> Hi @neomatrix369 - thanks for opening this issue!
> 
> nbQA simply applies any standard Python code quality tool to a Jupyter Notebook - if you have a Python tool which calculates complexity, then using nbQA it should be possible to apply it to a notebook.
> 
> Do you know of any Python tool for calculating complexity?

Cool so it's configurable! Nice!

I came across [Radon](https://audiolion.github.io/python/2016/10/17/reducing-cyclomatic-complexity.html) but there might be others. As long as we can get some score it helps.

**Comment by girip11** [comment] 2020-09-24 13:12
You might find this useful [Radon usage with Jupyter Notebooks](https://radon.readthedocs.io/en/latest/commandline.html#usage-with-jupyter-notebooks)

**Comment by neomatrix369** [comment] 2020-09-24 16:45
> You might find this useful [Radon usage with Jupyter Notebooks](https://radon.readthedocs.io/en/latest/commandline.html#usage-with-jupyter-notebooks)

Thanks for the response but I raised this question, I was inquiring to see if this would/could be a part of the QA checks already performed by nbQA! I can run these separately but an option to do it via the tool itself can be helpful.

Any thoughts on this?

**Comment by MarcoGorelli** [comment] 2020-09-24 16:53
Thanks for the suggestion @neomatrix369 !

If `radon` already supports Jupyter Notebooks out of the box, then IMO we don't need to support it here.

nbQA is meant as an adapter which allows Python-only tools to be run on Jupyter Notebooks - ideally, all the tools I love using (e.g. pylint, flake8, pyupgrade, etc.) would work out-of-the-box on Jupyter Notebooks, but until they do, I'm stuck running them via nbQA :)

Anyway, I'm grateful for the suggestion, but as `radon` is a rare example of a tool which works automatically on Jupyter Notebooks, I think we should consider it out-of-scope

**Comment by s-weigand** [comment] 2020-09-24 19:20
Maybe extending the aim of the project from:
> nbQA is meant as an adapter which allows Python-only tools to be run on Jupyter Notebooks

To:
```
A Tool wrapper to allow using your favorite Python QA tools with jupyter notebooks
```
Might be worth a thought.

I.e. for tools that already support jupyter notebooks like `radon`, `nbQA` just skip the parsing+change file steps and simply call the tool with the appropriate flag.

The big **con** with an approach like that, is that `nbQA` will get issues, caused by another tool, causing `issue redirect work` for the devs.

**Comment by MarcoGorelli** [comment] 2020-09-25 06:39
Thanks @s-weigand for the suggestion! Your idea makes sense, but I don't have much time to work on this project and would prefer to not expand the scope too much - if a tool already supports Jupyter Notebooks out-of-the-box, IMO there's no need to duplicate work.

Closing for now as out-of-scope then, but I'd like to re-iterate that I _really_ appreciate the suggestions made here

**Closed by MarcoGorelli** 2020-09-25 06:39 UTC

**Comment by MarcoGorelli** [comment] 2020-09-25 06:41
@all-contributors please add @neomatrix369 for ideas

**Comment by neomatrix369** [comment] 2020-10-15 13:34
Here are some formatting related resources I found, which may help with our discussions (the ones I raised previously):

- Python Zero to Hero - Ep.12 - Python linting and auto-formating: https://dev.to/cheukting_ho/python-zero-to-hero-ep-12-python-linting-and-auto-formating-p55
- Joe Gordon - Syntax Trees and Python - Automated Code Transformations - PyCon 2019: https://www.youtube.com/watch?v=viNzD1zD-Fg

**Comment by MarcoGorelli** [comment] 2020-10-15 13:39
Thanks @neomatrix369 !

> flake8, autoflake, black and isort.

We already have support for flake8, black, and isort, but we should add autoflake as it can be pretty useful

**Comment by neomatrix369** [comment] 2020-10-15 13:57
@MarcoGorelli I updated the above with more links

**Comment by neomatrix369** [comment] 2020-10-16 11:26
_Suggestion_

It's me again, this time I found something that will help our code base itself, I have installed @source-ai as a github action, see the report it generates https://github.com/neomatrix369/nlp_profiler/pull/27#issuecomment-709986856, pretty cool hey!

**Comment by MarcoGorelli** [comment] 2020-10-16 11:30
Wow, nice, thanks for bringing this to our attention! Do you want to add it as a github action here?

BTW pylint issue is resolved if you want to update your caching PR

**Comment by neomatrix369** [comment] 2020-10-16 13:22
> Wow, nice, thanks for bringing this to our attention! Do you want to add it as a github action here?
> 
> BTW pylint issue is resolved if you want to update your caching PR

Yes it's worth adding it as a github action, let me do it. I know the two founders from my past endeavours - I'm testing their offerings and also reporting with feedback.

Also look at this one https://github.com/sourcery-ai/python-best-practices-cookiecutter - lots of things to look at and use to verify our own flow

**Comment by neomatrix369** [comment] 2020-10-16 13:23
I just updated my branch, lets see what happens!

**Comment by neomatrix369** [comment] 2020-10-16 13:39
@MarcoGorelli just requested Sourcery-ai to be installed on nbQA-dev, one of the owners/admin users will need to approve it and then we have it integrated as part of the workflow just like it has done for my repo.

**Comment by neomatrix369** [comment] 2020-10-17 16:21
Adding one more to the list https://www.codeac.io/ - its things Sourcery-ai does not do I have already added to my repo (I know the devs to this one as well)

**Comment by MarcoGorelli** [comment] 2020-10-17 17:21
Cool, thanks for all these resources you've been linking, they'll be really useful!

**Comment by neomatrix369** [comment] 2020-10-17 17:45
> Adding one more to the list https://www.codeac.io/ - its things Sourcery-ai does not do I have already added to my repo (I know the devs to this one as well)

Their analysis is very comprehensive, they are basing it on their own tools and also external ones I think. Have a place to see what you think about it.

**Comment by neomatrix369** [comment] 2020-10-17 17:46
Did I share this ever?
https://github.com/analysis-tools-dev/static-analysis/blob/master/README.md#python

It's highly likely you have covered a bunch of them and others might be worth looking into as well when time permits.

**Comment by MarcoGorelli** [comment] 2020-10-17 17:53
that's a lot of tools, thanks! I'd like to see how many we can support
