### ISSUE TITLE
Tests don't pass if run in random order (bug?)

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#473] opened 2020-11-21 16:13 UTC
Steps to reproduce:

1. `rm -rf .tox`
2. add `pytest-randomly` to `requirements-dev.txt`
3 run `tox -e py` a few times

Example of order which fails:
```
tests/test_find_root.py::test_find_project_root[src0] PASSED                                                                                                                                       [  1%]
tests/test_find_root.py::test_find_project_root_no_root PASSED                                                                                                                                     [  2%]
tests/test_find_root.py::test_find_project_root[src1] PASSED                                                                                                                                       [  4%]
tests/test_no_inits.py::test_no_inits PASSED                                                                                                                                                       [  5%]
tests/test_setupcfg.py::test_nbqa_ini_works PASSED                                                                                                                                                 [  7%]
tests/test_cmdline.py::test_cli_command_str PASSED                                                                                                                                                 [  8%]
tests/tools/test_black.py::test_black_multiple_files PASSED                                                                                                                                        [  9%]
tests/tools/test_black.py::test_black_works PASSED                                                                                                                                                 [ 11%]
tests/tools/test_black.py::test_successive_runs_using_black PASSED                                                                                                                                 [ 12%]
tests/tools/test_black.py::test_black_works_with_multiline PASSED                                                                                                                                  [ 14%]
tests/tools/test_black.py::test_black_works_with_trailing_semicolons PASSED                                                                                                                        [ 15%]
tests/test_map_python_line_to_nb_lines.py::test_black_unparseable_output PASSED                                                                                                                    [ 16%]
tests/test_map_python_line_to_nb_lines.py::test_map_python_line_to_nb_lines PASSED                                                                                                                 [ 18%]
tests/test_get_notebooks.py::test_get_notebooks[_build] PASSED                                                                                                                                     [ 19%]
tests/test_get_notebooks.py::test_get_notebooks[venv] PASSED                                                                                                                                       [ 21%]
tests/test_get_notebooks.py::test_get_notebooks[.git] PASSED                                                                                                                                       [ 22%]
tests/tools/test_doctest.py::test_doctest_invalid_import PASSED                                                                                                                                    [ 23%]
tests/tools/test_doctest.py::test_doctest_works PASSED                                                                                                                                             [ 25%]
tests/test_create_blank_init_files.py::test_create_blank_init_files PASSED                                                                                                                         [ 26%]
tests/test_runtime_errors.py::test_unable_to_parse PASSED                                                                                                                                          [ 28%]
tests/test_runtime_errors.py::test_directory_without_notebooks PASSED                                                                                                                              [ 29%]
tests/test_runtime_errors.py::test_unable_to_parse_output PASSED                                                                                                                                   [ 30%]
tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath FAILED                                                                                                                 [ 32%]
tests/test_runtime_errors.py::test_missing_root_dir PASSED                                                                                                                                         [ 33%]
tests/test_runtime_errors.py::test_unable_to_reconstruct_message PASSED                                                                                                                            [ 35%]
tests/test_runtime_errors.py::test_missing_command PASSED                                                                                                                                          [ 36%]
tests/test_include_exclude.py::test_cli_files PASSED                                                                                                                                               [ 38%]
tests/test_include_exclude.py::test_config_files PASSED                                                                                                                                            [ 39%]
tests/test_include_exclude.py::test_config_exclude PASSED                                                                                                                                          [ 40%]
tests/test_include_exclude.py::test_cli_exclude PASSED                                                                                                                                             [ 42%]
tests/test_pyproject_toml.py::test_pyproject_toml_works PASSED                                                                                                                                     [ 43%]
tests/test_nbqa_diff.py::test_diff_present PASSED                                                                                                                                                  [ 45%]
tests/test_nbqa_diff.py::test_diff_and_mutate PASSED                                                                                                                                               [ 46%]
tests/test_ipython_magics.py::test_ignore_cells[[tool.nbqa.ignore_cells]\nflake8=["%%custommagic", "%%anothercustommagic"]-_validate_ignore_cells_without_warning-pyproject.toml] PASSED           [ 47%]
tests/test_ipython_magics.py::test_ignore_cells[[flake8]\nignore_cells=%%%%custommagic,%%%%anothercustommagic-_validate_ignore_cells_without_warning-.nbqa.ini] PASSED                             [ 49%]
tests/test_ipython_magics.py::test_indented_magics[[tool.nbqa.mutate]\nblack=1-_validate_magics_with_black-pyproject.toml] PASSED                                                                  [ 50%]
tests/test_ipython_magics.py::test_ignore_cells[--nbqa-ignore-cells=%%custommagic-_validate_ignore_cells_with_warning-None] PASSED                                                                 [ 52%]
tests/test_ipython_magics.py::test_ignore_cells[[tool.nbqa.ignore_cells]\nflake8=["%%custommagic"]-_validate_ignore_cells_with_warning-pyproject.toml] PASSED                                      [ 53%]
tests/test_ipython_magics.py::test_magics_with_flake8[--extend-ignore=F821-_validate_magics_flake8_warnings] PASSED                                                                                [ 54%]
tests/test_ipython_magics.py::test_ignore_cells[[flake8]\nignore_cells=%%%%custommagic-_validate_ignore_cells_with_warning-.nbqa.ini] PASSED                                                       [ 56%]
tests/test_ipython_magics.py::test_ignore_cells[--nbqa-ignore-cells=%%custommagic,%%anothercustommagic-_validate_ignore_cells_without_warning-None] PASSED                                         [ 57%]
tests/tools/test_mypy_works.py::test_mypy_works PASSED                                                                                                                                             [ 59%]
tests/test_configs_work.py::test_configs_work_in_setupcfg PASSED                                                                                                                                   [ 60%]
tests/test_configs_work.py::test_configs_work PASSED                                                                                                                                               [ 61%]
tests/test_configs_work.py::test_nonexistent_config PASSED                                                                                                                                         [ 63%]
tests/test_configs_work.py::test_setupcfg_is_preserved PASSED                                                                                                                                      [ 64%]
tests/test_configs_work.py::test_configs_work_in_nbqaini PASSED                                                                                                                                    [ 66%]
tests/tools/test_isort_works.py::test_isort_trailing_semicolon PASSED                                                                                                                              [ 67%]
tests/tools/test_isort_works.py::test_old_isort PASSED                                                                                                                                             [ 69%]
tests/tools/test_isort_works.py::test_isort_separated_imports[notebook_with_separated_imports_other.ipynb] PASSED                                                                                  [ 70%]
tests/tools/test_isort_works.py::test_isort_works PASSED                                                                                                                                           [ 71%]
tests/tools/test_isort_works.py::test_isort_separated_imports[notebook_with_separated_imports.ipynb] PASSED                                                                                        [ 73%]
tests/tools/test_isort_works.py::test_isort_initial_md PASSED                                                                                                                                      [ 74%]
tests/tools/test_isort_works.py::test_old_isort_separated_imports PASSED                                                                                                                           [ 76%]
tests/test_file_not_found.py::test_file_not_found PASSED                                                                                                                                           [ 77%]
tests/tools/test_autoflake.py::test_autoflake_toml PASSED                                                                                                                                          [ 78%]
tests/tools/test_autoflake.py::test_autoflake_cli PASSED                                                                                                                                           [ 80%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg1-cwd1] PASSED                                                                                                    [ 81%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg2-cwd2] PASSED                                                                                                    [ 83%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg0-cwd0] PASSED                                                                                                    [ 84%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg3-cwd3] PASSED                                                                                                    [ 85%]
tests/test_return_code.py::test_pylint_return_code PASSED                                                                                                                                          [ 87%]
tests/test_return_code.py::test_black_return_code PASSED                                                                                                                                           [ 88%]
tests/test_return_code.py::test_flake8_return_code PASSED                                                                                                                                          [ 90%]
tests/test_return_code.py::test_check_ast_return_code PASSED                                                                                                                                       [ 91%]
tests/test_return_code.py::test_autoflake_return_code PASSED                                                                                                                                       [ 92%]
tests/tools/test_pyupgrade.py::test_pyupgrade PASSED                                                                                                                                               [ 94%]
tests/test_allow_mutation.py::test_allow_mutation PASSED                                                                                                                                           [ 95%]
tests/test_version.py::test_version PASSED                                                                                                                                                         [ 97%]
tests/tools/test_pylint_works.py::test_pylint_works PASSED                                                                                                                                         [ 98%]
tests/tools/test_flake8_works.py::test_flake8_works PASSED          
```

example of order which passes:
```
tests/test_return_code.py::test_pylint_return_code PASSED                                                                                                                                          [  1%]
tests/test_return_code.py::test_autoflake_return_code PASSED                                                                                                                                       [  2%]
tests/test_return_code.py::test_flake8_return_code PASSED                                                                                                                                          [  4%]
tests/test_return_code.py::test_black_return_code PASSED                                                                                                                                           [  5%]
tests/test_return_code.py::test_check_ast_return_code PASSED                                                                                                                                       [  7%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg0-cwd0] PASSED                                                                                                    [  8%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg3-cwd3] PASSED                                                                                                    [  9%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg2-cwd2] PASSED                                                                                                    [ 11%]
tests/test_running_from_different_dir.py::test_running_in_different_dir_works[arg1-cwd1] PASSED                                                                                                    [ 12%]
tests/test_setupcfg.py::test_nbqa_ini_works PASSED                                                                                                                                                 [ 14%]
tests/test_allow_mutation.py::test_allow_mutation PASSED                                                                                                                                           [ 15%]
tests/tools/test_flake8_works.py::test_flake8_works PASSED                                                                                                                                         [ 16%]
tests/test_create_blank_init_files.py::test_create_blank_init_files PASSED                                                                                                                         [ 18%]
tests/tools/test_doctest.py::test_doctest_works PASSED                                                                                                                                             [ 19%]
tests/tools/test_doctest.py::test_doctest_invalid_import PASSED                                                                                                                                    [ 21%]
tests/test_map_python_line_to_nb_lines.py::test_black_unparseable_output PASSED                                                                                                                    [ 22%]
tests/test_map_python_line_to_nb_lines.py::test_map_python_line_to_nb_lines PASSED                                                                                                                 [ 23%]
tests/test_get_notebooks.py::test_get_notebooks[_build] PASSED                                                                                                                                     [ 25%]
tests/test_get_notebooks.py::test_get_notebooks[venv] PASSED                                                                                                                                       [ 26%]
tests/test_get_notebooks.py::test_get_notebooks[.git] PASSED                                                                                                                                       [ 28%]
tests/tools/test_isort_works.py::test_isort_separated_imports[notebook_with_separated_imports_other.ipynb] PASSED                                                                                  [ 29%]
tests/tools/test_isort_works.py::test_isort_trailing_semicolon PASSED                                                                                                                              [ 30%]
tests/tools/test_isort_works.py::test_isort_initial_md PASSED                                                                                                                                      [ 32%]
tests/tools/test_isort_works.py::test_isort_separated_imports[notebook_with_separated_imports.ipynb] PASSED                                                                                        [ 33%]
tests/tools/test_isort_works.py::test_old_isort PASSED                                                                                                                                             [ 35%]
tests/tools/test_isort_works.py::test_isort_works PASSED                                                                                                                                           [ 36%]
tests/tools/test_isort_works.py::test_old_isort_separated_imports PASSED                                                                                                                           [ 38%]
tests/test_include_exclude.py::test_cli_exclude PASSED                                                                                                                                             [ 39%]
tests/test_include_exclude.py::test_cli_files PASSED                                                                                                                                               [ 40%]
tests/test_include_exclude.py::test_config_exclude PASSED                                                                                                                                          [ 42%]
tests/test_include_exclude.py::test_config_files PASSED                                                                                                                                            [ 43%]
tests/tools/test_black.py::test_successive_runs_using_black PASSED                                                                                                                                 [ 45%]
tests/tools/test_black.py::test_black_works_with_multiline PASSED                                                                                                                                  [ 46%]
tests/tools/test_black.py::test_black_works PASSED                                                                                                                                                 [ 47%]
tests/tools/test_black.py::test_black_multiple_files PASSED                                                                                                                                        [ 49%]
tests/tools/test_black.py::test_black_works_with_trailing_semicolons PASSED                                                                                                                        [ 50%]
tests/test_ipython_magics.py::test_ignore_cells[[flake8]\nignore_cells=%%%%custommagic,%%%%anothercustommagic-_validate_ignore_cells_without_warning-.nbqa.ini] PASSED                             [ 52%]
tests/test_ipython_magics.py::test_ignore_cells[[tool.nbqa.ignore_cells]\nflake8=["%%custommagic", "%%anothercustommagic"]-_validate_ignore_cells_without_warning-pyproject.toml] PASSED           [ 53%]
tests/test_ipython_magics.py::test_ignore_cells[--nbqa-ignore-cells=%%custommagic,%%anothercustommagic-_validate_ignore_cells_without_warning-None] PASSED                                         [ 54%]
tests/test_ipython_magics.py::test_ignore_cells[[flake8]\nignore_cells=%%%%custommagic-_validate_ignore_cells_with_warning-.nbqa.ini] PASSED                                                       [ 56%]
tests/test_ipython_magics.py::test_ignore_cells[[tool.nbqa.ignore_cells]\nflake8=["%%custommagic"]-_validate_ignore_cells_with_warning-pyproject.toml] PASSED                                      [ 57%]
tests/test_ipython_magics.py::test_magics_with_flake8[--extend-ignore=F821-_validate_magics_flake8_warnings] PASSED                                                                                [ 59%]
tests/test_ipython_magics.py::test_indented_magics[[tool.nbqa.mutate]\nblack=1-_validate_magics_with_black-pyproject.toml] PASSED                                                                  [ 60%]
tests/test_ipython_magics.py::test_ignore_cells[--nbqa-ignore-cells=%%custommagic-_validate_ignore_cells_with_warning-None] PASSED                                                                 [ 61%]
tests/tools/test_mypy_works.py::test_mypy_works PASSED                                                                                                                                             [ 63%]
tests/test_pyproject_toml.py::test_pyproject_toml_works PASSED                                                                                                                                     [ 64%]
tests/tools/test_autoflake.py::test_autoflake_toml PASSED                                                                                                                                          [ 66%]
tests/tools/test_autoflake.py::test_autoflake_cli PASSED                                                                                                                                           [ 67%]
tests/tools/test_pylint_works.py::test_pylint_works PASSED                                                                                                                                         [ 69%]
tests/test_file_not_found.py::test_file_not_found PASSED                                                                                                                                           [ 70%]
tests/test_runtime_errors.py::test_unable_to_parse PASSED                                                                                                                                          [ 71%]
tests/test_runtime_errors.py::test_missing_command PASSED                                                                                                                                          [ 73%]
tests/test_runtime_errors.py::test_unable_to_parse_output PASSED                                                                                                                                   [ 74%]
tests/test_runtime_errors.py::test_directory_without_notebooks PASSED                                                                                                                              [ 76%]
tests/test_runtime_errors.py::test_missing_root_dir PASSED                                                                                                                                         [ 77%]
tests/test_runtime_errors.py::test_unable_to_reconstruct_message PASSED                                                                                                                            [ 78%]
tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath PASSED                                                                                                                 [ 80%]
tests/test_find_root.py::test_find_project_root[src0] PASSED                                                                                                                                       [ 81%]
tests/test_find_root.py::test_find_project_root[src1] PASSED                                                                                                                                       [ 83%]
tests/test_find_root.py::test_find_project_root_no_root PASSED                                                                                                                                     [ 84%]
tests/test_version.py::test_version PASSED                                                                                                                                                         [ 85%]
tests/test_configs_work.py::test_configs_work PASSED                                                                                                                                               [ 87%]
tests/test_configs_work.py::test_nonexistent_config PASSED                                                                                                                                         [ 88%]
tests/test_configs_work.py::test_setupcfg_is_preserved PASSED                                                                                                                                      [ 90%]
tests/test_configs_work.py::test_configs_work_in_nbqaini PASSED                                                                                                                                    [ 91%]
tests/test_configs_work.py::test_configs_work_in_setupcfg PASSED                                                                                                                                   [ 92%]
tests/tools/test_pyupgrade.py::test_pyupgrade PASSED                                                                                                                                               [ 94%]
tests/test_cmdline.py::test_cli_command_str PASSED                                                                                                                                                 [ 95%]
tests/test_nbqa_diff.py::test_diff_and_mutate PASSED                                                                                                                                               [ 97%]
tests/test_nbqa_diff.py::test_diff_present PASSED                                                                                                                                                  [ 98%]
tests/test_no_inits.py::test_no_inits PASSED                                                                                                                                                       [100%]
```

In the failing case, here's the error:
```
FAILED tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath - ModuleNotFoundError: Command `remove_comments` not found by nbqa.
```

**Comment by s-weigand** [comment] 2020-11-22 15:45
Might it be that this tests is just missing the proper fixture ?
Compare:
https://github.com/nbQA-dev/nbQA/blob/e5f4e43919da233b9f8b0d7bd65a5ccef0c67631/tests/test_runtime_errors.py#L74-L76

to
https://github.com/nbQA-dev/nbQA/blob/e5f4e43919da233b9f8b0d7bd65a5ccef0c67631/tests/test_runtime_errors.py#L84-L85

At least this would explain why it fails if `test_unable_to_reconstruct_message` wasn't called before (I think the default scope of fixtures is module).

https://github.com/nbQA-dev/nbQA/blob/e5f4e43919da233b9f8b0d7bd65a5ccef0c67631/tests/conftest.py#L182-L188

**Comment by s-weigand** [comment] 2020-11-22 15:59
A quick test with
```console
$ pytest tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath
```

Shows that it fails on master, but passes if you add the fixture.

**Comment by s-weigand** [comment] 2020-11-22 16:15
From the pytest results you can also see that in the failing case `test_unable_to_reconstruct_message` was executed after `test_unable_to_reconstruct_message_pythonpath`.

```
tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath FAILED
tests/test_runtime_errors.py::test_missing_root_dir PASSED
tests/test_runtime_errors.py::test_unable_to_reconstruct_message PASSED 
```

```
tests/test_runtime_errors.py::test_unable_to_reconstruct_message PASSED 
tests/test_runtime_errors.py::test_unable_to_reconstruct_message_pythonpath PASSED
```

**Comment by MarcoGorelli** [comment] 2020-11-22 16:39
I don't think this is the right fix though - the purpose of this test is to check that we are still able to access `reconstruct_message` if it's in the PYTHONPATH though not necessarily in the current working directory, so moving it to the current directory (via this fixture) defeats its purpose

I don't really understand why running `test_unable_to_reconstruct_message` before it makes it pass though...I'll try to dig deeper

**Comment by s-weigand** [comment] 2020-11-22 18:02
Ohh looks like I misunderstood the purpose of the test. 😞 

And I think i got an explanaiton why running `test_unable_to_reconstruct_message` first has the test passing.
My guess is that after running `test_unable_to_reconstruct_message` `remove_comments` is in the module cache (`sys.modules`), thus python doesn't try to resolve it a second time, but uses the cached version.

**Comment by s-weigand** [comment] 2020-11-22 18:17
A quick test confirms that removing `remove_comments` from the module cache can reproduce the problem for the before working execution order.

For quick testing:
- working test order: `pytest --randomly-seed=3001700012 -vv`
- failing test order `pytest --randomly-seed=1379466069 -vv`

Adding:
```python
del sys.modules["remove_comments"]
```
to the cleanup of `tmp_remove_comments`, preproduces the the error for the working order.

**Comment by MarcoGorelli** [comment] 2020-11-22 18:22
Awesome, thanks for much for your investigation! Maybe we could add `def sys.modules` as an autouse fixture, so at the tests always fail. Then we can mark this one as xfail (strict) and sort it out in the future

**Comment by s-weigand** [comment] 2020-11-22 20:06
Ok, I guess I figured out why the test is failing.

The problem is that `_check_command_is_installed` isn't using `PYTHONPATH` and thus is throwing an error.
If we monkey patch it out
```python
monkeypatch.setattr(nbqa.__main__, "_check_command_is_installed", lambda command: None)
```
The test passes.

The other option would be setting the env var in tox:
```ini
[testenv]
setenv   =
    PYTHONPATH = {toxinidir}/tests
```
CONS:
- this would apply to all tests and may cause side effects
- we can't simply use `pytest` directly from the dev env

Since this is a synthetic test (since python would behave differently if `PYTHONPATH` was set), I think that monkey patching `_check_command_is_installed` for this one test is reasonable.
Hence that setting `PYTHONPATH` only changes what happens when initializing python (see [this answer](https://stackoverflow.com/a/3108307/3990615) and the [first line pythons documentation](https://docs.python.org/3/using/cmdline.html#environment-variables)).
When running the command this is done by setting the `env` for the subprocess
https://github.com/nbQA-dev/nbQA/blob/2eefdf4ec5fb579732734c66576afd93676a7b90/nbqa/__main__.py#L411-L426

**Comment by s-weigand** [comment] 2020-11-22 20:33
@MarcoGorelli if I understood you right you want to reset `sys.modules` after each test?

I think this would slow down the tests a lot since python would need to load the modules over and over again.

A quick summary of what happens when python imports something:
1. Python checks if `sys.modules` has an entry with that name, if it does it uses it and is done.
1. If there was no module Python tries all import_hooks in order and the first one resolving a module with that name adds it and all its imported submodules/dependecies to `sys.modules`.

The first step is the reason why using the same import in multiple files doesn't produce a big overhead and why many beginners get problems when they want to try out a module/package in a file with the same name. 😝

**Comment by s-weigand** [comment] 2020-11-23 00:18
Oh, another option to fix the test would be to call `python -m nbqa` with the proper flags + env and parse the output.

**Comment by s-weigand** [comment] 2020-11-23 12:10
@MarcoGorelli Which approach do you prefer?

Since this isn't a test for checking if a command is installed, IMHO monkey patching  `_check_command_is_installed` would be legit.

While calling it with `subprocess.run` would be closer to what actually happens when using `nbqa` with a set `PYTHONPATH`.

**Comment by MarcoGorelli** [comment] 2020-11-23 12:13
If the latter (subprocess.run) works, then that might be better - thanks! The first is fine too though

**Closed** 2020-11-24 16:10 UTC
